### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by janosimas** [aunetx/text-translator#1]
Hi,
I just found your project and it would be a nice improvement for my current toy project.
Are you willing to continue with it?
I'll try to open a pull request with a simple version for Google translate this week.

**Comment by janosimas** [comment]
Yes, there is more than one option from what I understood but you'll need some king of key.

**Comment by janosimas** [comment]
I added support for language detection on the google api

**Comment by janosimas** [comment]
I also made a small cli aplication for testing the features [text-translator-cli](https://github.com/janosimas/text-translator-cli)

**Comment by aunetx** [comment]
Thanks a lot for all your changes! I added you as a collaborator so you can merge/commit to the project yourself (as I don't have any time right now).

If you don't mind, I suggest you to write some tests (and disable/remove the ones I wrote for the Yandex API).
I will write a new version of the Yandex API methods to cover both ancient and new versions, but I will need some time as I need to work aside. If you want to try to reimplement it, feel free to create a new branch!
